
image: gitpod/workspace-full

ports:
  - port: 5000
    onOpen: open-browser
    visibility: public

tasks:
  - init: npm install
    command: npm run dev

vscode:
  extensions:
    - svelte.svelte-vscode
    - github.vscode-pull-request-github
    - ms-azuretools.vscode-docker
